config/routes.rb
Rails.application.routes.draw do
  root to: "application#index"
  devise_for :users do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  
  resources :musics
  get 'user/profile'
  get 'suggestions/suggestions'
  get 'top_five/topfive'
  get 'top_five/suggestion'
  post 'music', to: 'music#create'
  post 'top_five/topfive'
  post 'user/id'
  patch "user/update"
  get '/user/show'
  get 'user/profile'
  
  resources :user do

    patch :update

  end



  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/music.rb
class Music < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
protect_from_forgery with: :null_session
before_action :configure_permitted_parameters, if: :devise_controller?

def index

   if(current_user.nil?)
         redirect_to '/users/sign_in'
  else
  @music = Music.all.to_s
  @user = User.where(id: devise_current_user.id)
  @rank1 = User.select("rank1").where(id: devise_current_user)
  #@rank2 = @user.rank2
  #@rank3 = @user.rank3
  #@rank4 = @user.rank4
  #@rank5 = @user.rank5
  end

  @musicname1 = Music.select("song_name").where(id: @rank1)
  @musicdecade1 = Music.select("decade").where(id:@rank1)
  #@musicrank2 = @music.where(id: @rank2)
  #@musicrank3 = @music.where(id: @rank3)
  #@musicrank4 = @music.where(id: @rank4)
  #@musicrank5 = @music.where(id: @rank5)
end



def devise_current_user
  @devise_current_user ||= warden.authenticate(scope: :user)
end

def current_user
  if params[:user_id].blank?
    devise_current_user
  else
    User.find(params[:user_id])
  end   
end
  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:region])
  end
end

app/controllers/musics_controller.rb
class MusicsController < ApplicationController
  before_action :set_music, only: %i[ show edit update destroy ]

  # GET /musics or /musics.json
  def index
    @musics = Music.all
  end

  # GET /musics/1 or /musics/1.json
  def show
  end

  # GET /musics/new
  def new
    @music = Music.new
  end

  # GET /musics/1/edit
  def edit
  end

  # POST /musics or /musics.json
  def create
    @music = Music.new(music_params)

    respond_to do |format|
      if @music.save
        format.html { redirect_to music_url(@music), notice: "Music was successfully created." }
        format.json { render :show, status: :created, location: @music }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @music.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /musics/1 or /musics/1.json
  def update
    respond_to do |format|
      if @music.update(music_params)
        format.html { redirect_to music_url(@music), notice: "Music was successfully updated." }
        format.json { render :show, status: :ok, location: @music }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @music.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /musics/1 or /musics/1.json
  def destroy
    @music.destroy

    respond_to do |format|
      format.html { redirect_to musics_url, notice: "Music was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_music
      @music = Music.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def music_params
      params.require(:music).permit(:song_name, :song_popularity, :points)
    end
end

app/controllers/suggestions_controller.rb
class SuggestionsController < ApplicationController
  def suggestions
  end
end

app/controllers/top_five_controller.rb
class TopFiveController < ApplicationController
  def topfive
    @user = current_user
    @music = Music.all
  end

  def suggestion
  end

  def create
    
    puts params.require(:music).permit(songs: [])
    redirect_to music_path(@music), notice: "Music successfully created"

  end
end

app/controllers/top_ten_controller.rb
class TopFiveController < ApplicationController
  def topfive
    @user = current_user
    @music = Music.all
  end

  def suggestion
  end

  def create
    
    puts params.require(:music).permit(songs: [])
    redirect_to music_path(@music), notice: "Music successfully created"

  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  
  attr_accessor :id, :email, :region, :created_at, :updated_at, :rank1, :rank2, :rank3, :rank4, :rank5
  def profile
  end

  def show
    @user = User.find[params[:id]]
  end

  def update
    user = User.find(devise_current_user.id)
    @parameters = params[:user]
    user = User.where(id: user.id).update_all(rank1: @parameters[:rank1], rank2: @parameters[:rank2], rank3: @parameters[:rank3], rank4: @parameters[:rank4], rank5: @parameters[:rank5])    
    redirect_to root_path, alert: "Your rankings have been saved!"
  end
  private
  def topfiveparams #This is for permitted params
    params.require(:user).permit(:email, :region, :rank1, :rank2, :rank3, :rank4, :rank5)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/musics_helper.rb
module MusicsHelper
end

app/helpers/suggestions_helper.rb
module SuggestionsHelper
end

app/helpers/top_five_helper.rb
module TopFiveHelper
end

app/helpers/top_ten_helper.rb
module TopFiveHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/application/index.html.erb
<body>

<style>    
body {    
  height: 1000px;  
  background-color: #cccccc;  
  background-image: linear-gradient(rgba(0, 0, 255, 0.5),rgba(255, 255, 0, 0.5)), url("images/Cultural_Cadence.png");  
}  
</style>   
    <%= button_to "Click here to choose and rank your top five favorite songs!", top_five_topfive_path(current_user.id)  %>

<table class="table table-hover">
    <tr>
        <th>Ranking</th>
        <th>Song</th>
        <th>Decade</th>
    </tr>

<tr>                
    
  <% @rank1.each do |rank| %>                    
  <td><%= rank %><td>
<% end %>

<% @musicname1.each do |name| %>
  <td><%= name %></td>
<% end %>

<% @musicdecade1.each do |decade| %>
  <td><%= decade %></td>
<% end %>
                  
</tr>
</table>
 </body>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cultural Cadence</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css" integrity="sha512-MV7K8+y+gLIBoVD59lQIYicR65iaqukzvf/nwasF0nqhPay5w/9lJmVM2hMDcnK1OnMGCdVK+iQrJ7lzPJQd1w==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <style> 
    height: 200px;  
    background-color: #ffff;
    background-image: radial-gradient(red, green, yellow); }  
  </style>

  <body>
  <!-- NavBar -->
  
  <div class="navbar">
    <div class="container flex">
      <h1 class="logo">Cultural Cadence</h1>
      <nav> 
        <ul> 
          <% if user_signed_in? %>
           <li> Logged in as <strong><%= current_user.email %></strong> |</li>
            <li><%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> </li>
            <li> <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %> </li>
          <% else %>
           <li> <a> <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> </a> </li>
           <li> <a> <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %> </a> </li>
          <% end %>
        </ul>
      </nav>
    </div>
  </div>

<!--Navbar End -->
  <% if notice %>
    <p class="alert alert-success"><%= notice %></p>
  <% end %>
  <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
  <% end %>
    <%= yield %>
  </body>
</html>

app/views/musics/_form.html.erb
<%= form_with(model: music) do |form| %>
  <% if music.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(music.errors.count, "error") %> prohibited this music from being saved:</h2>

      <ul>
        <% music.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :song_name, style: "display: block" %>
    <%= form.text_field :song_name %>
  </div>

  <div>
    <%= form.label :song_popularity, style: "display: block" %>
    <%= form.number_field :song_popularity %>
  </div>

  <div>
    <%= form.label :points, style: "display: block" %>
    <%= form.number_field :points %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/musics/_music.html.erb
<div id="<%= dom_id music %>">
  <p>
    <strong>Song name:</strong>
    <%= music.song_name %>
  </p>

  <p>
    <strong>Song popularity:</strong>
    <%= music.song_popularity %>
  </p>

  <p>
    <strong>Points:</strong>
    <%= music.points %>
  </p>

</div>

app/views/musics/edit.html.erb
<h1>Editing music</h1>

<%= render "form", music: @music %>

<br>

<div>
  <%= link_to "Show this music", @music %> |
  <%= link_to "Back to musics", musics_path %>
</div>

app/views/musics/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Musics</h1>

<div id="musics">
  <% @musics.each do |music| %>
    <%= render music %>
    <p>
      <%= link_to "Show this music", music %>
    </p>
  <% end %>
</div>

<%= link_to "New music", new_music_path %>

app/views/musics/new.html.erb
<h1>New music</h1>

<%= render "form", music: @music %>

<br>

<div>
  <%= link_to "Back to musics", musics_path %>
</div>

app/views/musics/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @music %>

<div>
  <%= link_to "Edit this music", edit_music_path(@music) %> |
  <%= link_to "Back to musics", musics_path %>

  <%= button_to "Destroy this music", @music, method: :delete %>
</div>

app/views/suggestions/suggestions.html.erb
<h1>Suggestions#suggestions</h1>
<p>Find me in app/views/suggestions/suggestions.html.erb</p>

app/views/top_five/suggestion.html.erb
<label for="dog-names">Choose genre of music:</label>
<select name="dog-names" id="dog-names">
    <option value="Rap">Rap</option>
  <option value="Classical">Classical</option>
  <option value="Raagatton">Raagatton</option>
  <option value="Jazz">Jazz</option>
</select>


<p>What year's music do you want?</p>
<div class="slider">
<input type="range" min="1920" max="2023" value="2023" oninput="rangeValue.innerText = this.value">
<p id="rangeValue">2023</p>
</div>
<button type="button">Do it!</button>


<p>Press this button to get a song w/ same genre from a different region</p>

<button type="button">Do it!</button>


<p>Press this button to get a random genera of song from a random region</p>


<button type="button">Do it!</button>

app/views/top_five/topfive.html.erb
<h1>Select Your Top Five!</h1>
<%= form_for(current_user, url: user_update_path(current_user)) do |f| %> 
 

  <div class="field">
  <%=f.hidden_field :id, value: current_user.id%>
    <%= f.label :rank1 %><br />
    <%= f.select :rank1, options_from_collection_for_select(Music.all, :id, :song_name), { include_blank: true } %>
  </div>

  <div class="field">
    <%= f.label :rank2 %><br />
    <%= f.select :rank2, options_from_collection_for_select(Music.all, :id, :song_name), { include_blank: true } %>
  </div>

  <div class="field">
    <%= f.label :rank3 %><br />
    <%= f.select :rank3, options_from_collection_for_select(Music.all, :id, :song_name), { include_blank: true } %>
  </div>

  
  <div class="field">
    <%= f.label :rank4 %><br />
    <%= f.select :rank4, options_from_collection_for_select(Music.all, :id, :song_name), { include_blank: true } %>
  </div>
 
 
  <div class="field">
    <%= f.label :rank5 %><br />
    <%= f.select :rank5, options_from_collection_for_select(Music.all, :id, :song_name), { include_blank: true } %>
  </div>


  <br>
  
  <div class="actions">
    <%= f.submit "Update" %>
  </div>

  
<% end %>

<br>

<%= link_to "Back", :back %>

app/views/top_ten/topten.html.erb
<h1>Select Your Top Five!</h1>
<%= form_for(current_user, url: user_update_path(current_user)) do |f| %> 
 

  <div class="field">
  <%=f.hidden_field :id, value: current_user.id%>
    <%= f.label :rank1 %><br />
    <%= f.select :rank1, options_from_collection_for_select(Music.all, :id, :song_name), { include_blank: true } %>
  </div>

  <div class="field">
    <%= f.label :rank2 %><br />
    <%= f.select :rank2, options_from_collection_for_select(Music.all, :id, :song_name), { include_blank: true } %>
  </div>

  <div class="field">
    <%= f.label :rank3 %><br />
    <%= f.select :rank3, options_from_collection_for_select(Music.all, :id, :song_name), { include_blank: true } %>
  </div>

  
  <div class="field">
    <%= f.label :rank4 %><br />
    <%= f.select :rank4, options_from_collection_for_select(Music.all, :id, :song_name), { include_blank: true } %>
  </div>
 
 
  <div class="field">
    <%= f.label :rank5 %><br />
    <%= f.select :rank5, options_from_collection_for_select(Music.all, :id, :song_name), { include_blank: true } %>
  </div>


  <br>
  
  <div class="actions">
    <%= f.submit "Update" %>
  </div>

  
<% end %>

<br>

<%= link_to "Back", :back %>

app/views/user/profile.html.erb
<h1>User#profile</h1>
<p>Find me in app/views/user/profile.html.erb</p>